name: taskly-containers

services:
  otel-collector:
    image: otel/opentelemetry-collector
    volumes:
      - ../.config/otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension
  loki:
    image: grafana/loki:latest
    container_name: grafana-loki
    ports:
      - "3100:3100"
    volumes:
      - ../.config/loki/loki-config.yaml:/etc/loki/config.yaml
    command: -config.file=/etc/loki/config.yaml
    networks:
      - loki
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=grafanaManagedRecordingRules
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    ports:
      - "3000:3000"
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: 'http://loki:3100'
          basicAuth: false
          isDefault: true
          version: 1
          editable: true 
        EOF
        /run.sh
    networks:
      - loki
  alloy:
    image: grafana/alloy:latest
    container_name: grafana-alloy
    ports:
      - "12345:12345"
    volumes:
      - ../.config/loki/config.alloy:/etc/alloy/config.alloy
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - loki
    networks:
      - loki
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - mailtip-data:/data/mailtip
      - ../.config/mailtip:/etc/mailtip
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_SMTP_AUTH_FILE: /etc/mailtip/password
      MP_SMTP_TLS_CERT: /etc/mailtip/cert.pem
      MP_SMTP_TLS_KEY: /etc/mailtip/key.pem
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailtip/mailpit.db
      MP_SMTP_AUTH_ALLOW_INSECURE: true
  db:
    container_name: db
    restart: unless-stopped
    image: postgres:18
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    environment:
      POSTGRES_USER: taskly_user
      POSTGRES_PASSWORD: qwerty12345
      POSTGRES_DB: taskly_db
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U taskly_user -d taskly_db" ]
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - ../.config/init-db.sql:/docker-entrypoint-initdb.d/init.sql
      - ../.config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - pg_data:/var/lib/postgresql
  redis:
    container_name: taskly_redis
    restart: unless-stopped
    image: redis:8.10.1-alpine
    command:
      - "redis-server"
      - "/usr/local/etc/redis/redis.conf"
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    volumes:
      - ../.config/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ../.config/redis/users.acl:/usr/local/etc/redis/users.acl:ro
      - redis_data:/data
  redisinsight:
    container_name: taskly_redis_gui
    restart: unless-stopped
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/data

volumes:
  mailtip-data:
  pg_data:
  redis_data:
  redisinsight:

networks:
  loki: