name: taskly-containers

services:
  otel-collector:
    image: otel/opentelemetry-collector
    volumes:
      - ../.config/otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - mailtip-data:/data/mailtip
      - ../.config/mailtip:/etc/mailtip
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_SMTP_AUTH_FILE: /etc/mailtip/password
      MP_SMTP_TLS_CERT: /etc/mailtip/cert.pem
      MP_SMTP_TLS_KEY: /etc/mailtip/key.pem
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailtip/mailpit.db
      MP_SMTP_AUTH_ALLOW_INSECURE: true
  db:
    container_name: db
    restart: unless-stopped
    image: postgres:18
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    environment:
      POSTGRES_USER: taskly_user
      POSTGRES_PASSWORD: qwerty12345
      POSTGRES_DB: taskly_db
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
    volumes:
      - ../.config/init-db.sql:/docker-entrypoint-initdb.d/init.sql
      - ../.config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - pg_data:/var/lib/postgresql
  redis:
    container_name: taskly_redis
    restart: unless-stopped
    image: redis:8.10.1-alpine
    command:
      - "redis-server"
      - "/usr/local/etc/redis/redis.conf"
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    volumes:
      - ../.config/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ../.config/redis/users.acl:/usr/local/etc/redis/users.acl:ro
      - redis_data:/data

volumes:
  mailtip-data:
  pg_data:
  redis_data: